spring:
  data:
    mongodb:
      uri: mongodb+srv://user:xnmt4OWnwGQxEl6m@cluster0.aqjmgm9.mongodb.net/banking

  rabbitmq:
    addresses: amqps://nujwcdrx:ijnO3_pkjkb8Oq19KbLxWhwvVzWXNZmZ@leopard.lmq.cloudamqp.com/nujwcdrx
ledger:
  base-url: http://localhost:8081

loggin:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

server:
    port: 8081
